# Generated by Django 4.1.5 on 2023-05-26 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicantManager', '0002_applicantrole_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='applicantrole',
            unique_together={('role', 'applicant')},
        ),
    ]
